/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */

rootProject.name = "craftingInterpreters"
include("app")

pluginManagement {
    // https://discuss.gradle.org/t/how-can-i-publish-to-maven-the-plugin-defined-at-buildsrc/42039/2
    // https://docs.gradle.org/current/userguide/composite_builds.html#included_plugin_builds
    includeBuild("./expressionClassGeneratorPlugin")
}